# -*- coding: utf-8 -*-
"""anaslastResNet50Final+update.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1avI8F5w73InfFdB_PZzzpOCXX482FlGP
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive
#/content/drive/MyDrive/orginalproject/Training

!pwd

!ls

#%pip install opencv-python

"""# Images Preprocessing"""

import numpy as np
import cv2
import os
from tqdm import tqdm
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG19
from tensorflow.keras import layers, models, optimizers
import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %pip install tqdm

# Expected folder structure:
# Training/
# ├── glioma/
# ├── meningioma/
# ├── notumor/
# └── pituitary/
data_dir_Training = "/content/drive/MyDrive/orginalproject/Training"
data_dir_validation = "/content/drive/MyDrive/orginalproject/validation"
data_dir_brain_tumor_CLAHE = "/content/drive/MyDrive/brain_tumor_CLAHE"
data_dir_brain_tumor_validation_CLAHE = '/content/drive/MyDrive/brain_tumor_validation_CLAHE'
data_dir_brain_tumor_testing_CLAHE = '/content/drive/MyDrive/brain_tumor_testing_CLAHE'

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/orginalproject/Training/glioma/

# Reading the black and white image
img = cv2.imread('Tr-gl_0010.jpg', cv2.IMREAD_GRAYSCALE)
# Create a CLAHE object
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
# Apply CLAHE to the image
cl1 = clahe.apply(img)
# Show pictures for comparison
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
plt.title("Original Image")
plt.imshow(img, cmap='gray')

plt.subplot(1,2,2)
plt.title("CLAHE Algorithm Enhanced Image")
plt.imshow(cl1, cmap='gray')

plt.show()

# Black and white image reading
img = cv2.imread('Tr-gl_0010.jpg', cv2.IMREAD_GRAYSCALE)

# Create and apply a CLAHE object
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
cl1 = clahe.apply(img)

# Histogram Calculation
hist_original = cv2.calcHist([img], [0], None, [256], [0,256])
hist_clahe = cv2.calcHist([cl1], [0], None, [256], [0,256])

# Show results
plt.figure(figsize=(12,8))

# Original Image
plt.subplot(2,2,1)
plt.title("Original Image")
plt.imshow(img, cmap='gray')
plt.axis('off')

# Original Histogram
plt.subplot(2,2,2)
plt.title("Histogram - Original")
plt.plot(hist_original, color='gray')
plt.xlim([0,256])

# Picture after CLAHE
plt.subplot(2,2,3)
plt.title("CLAHE Enhanced Image")
plt.imshow(cl1, cmap='gray')
plt.axis('off')

# Histogram after CLAHE
plt.subplot(2,2,4)
plt.title("Histogram - CLAHE")
plt.plot(hist_clahe, color='gray')
plt.xlim([0,256])

plt.tight_layout()
plt.show()

# Original data folder
#input_dir v
data_dir_Training = "/content/drive/MyDrive/orginalproject/Training"

# New folder to save photos after applying CLAHE
output_dir = '/content/drive/MyDrive/brain_tumor_CLAHE'
os.makedirs(output_dir, exist_ok=True)

# Step 3: Apply the CLAHE algorithm to each image
for category in os.listdir(data_dir_Training):
    category_path = os.path.join(data_dir_Training, category)
    save_path = os.path.join(output_dir, category)
    os.makedirs(save_path, exist_ok=True)

    # Make sure the item is a folder (not a file)
    if not os.path.isdir(category_path):
        continue

    print(f" Processing category: {category}")

    for img_name in tqdm(os.listdir(category_path)):
        img_path = os.path.join(category_path, img_name)
        img = cv2.imread(img_path)

        if img is None:
            continue

        # Convert image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Create a CLAHE object
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
        cl1 = clahe.apply(gray)

        # Reset image to RGB (for compatibility with ImageDataGenerator)
        processed = cv2.cvtColor(cl1, cv2.COLOR_GRAY2BGR)

        # Save the resulting image
        cv2.imwrite(os.path.join(save_path, img_name), processed)

print(" CLAHE has been applied to all images and saved in : ")
print(output_dir)

# Original data folder
#input_dir v
data_dir_validation = "/content/drive/MyDrive/orginalproject/validation"

# New folder to save photos after applying CLAHE
output_dir = '/content/drive/MyDrive/brain_tumor_validation_CLAHE'
os.makedirs(output_dir, exist_ok=True)

# Step 3: Apply the CLAHE algorithm to each image
for category in os.listdir(data_dir_validation):
    category_path = os.path.join(data_dir_validation, category)
    save_path = os.path.join(output_dir, category)
    os.makedirs(save_path, exist_ok=True)

    # Make sure the item is a folder (not a file)
    if not os.path.isdir(category_path):
        continue

    print(f" Processing category: {category}")

    for img_name in tqdm(os.listdir(category_path)):
        img_path = os.path.join(category_path, img_name)
        img = cv2.imread(img_path)

        if img is None:
            continue

        # Convert image to grayscale
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        # Create a CLAHE object
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
        cl1 = clahe.apply(gray)

        # Reset image to RGB (for compatibility with ImageDataGenerator)
        processed = cv2.cvtColor(cl1, cv2.COLOR_GRAY2BGR)

        # Save the resulting image
        cv2.imwrite(os.path.join(save_path, img_name), processed)

print(" CLAHE file validation has been applied to all images and saved in : ")
print(output_dir)

"""# Model ResNet50 v1"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=5,
    width_shift_range=0.05,
    height_shift_range=0.05,
    zoom_range=0.1,
    brightness_range=[0.7, 1.2],
    horizontal_flip=True,
    fill_mode='nearest'
)
val_datagen = ImageDataGenerator(
    rescale=1./255
)


train_generator = train_datagen.flow_from_directory(
    data_dir_brain_tumor_CLAHE,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=True
)
validation_generator = val_datagen.flow_from_directory(
    data_dir_brain_tumor_validation_CLAHE,
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

import tensorflow as tf
from sklearn.metrics import f1_score
import numpy as np
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

IMG_SIZE = (224, 224)
num_classes = 4
learning_rate = 1e-4


# Model: ResNet50 + FT
base_model = tf.keras.applications.ResNet50(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3)
)

# Freeze all layers first
for layer in base_model.layers:
    layer.trainable = False

# Unfreeze last 2 blocks for fine tuning
for layer in base_model.layers:
    if "conv5_block" in layer.name or "conv4_block" in layer.name:
        layer.trainable = True

x = layers.GlobalAveragePooling2D()(base_model.output)

# dense + regularization
x = layers.Dense(256,activation="relu",kernel_regularizer=regularizers.l2(0.001))(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.2)(x)

outputs = layers.Dense(num_classes, activation="softmax")(x)
model = models.Model(inputs=base_model.input, outputs=outputs)

# compile
model.compile(
    optimizer=tf.keras.optimizers.AdamW(
        learning_rate=learning_rate,
        weight_decay=1e-4),
    loss="categorical_crossentropy",
    metrics=["accuracy",tf.keras.metrics.Precision(name="precision"),tf.keras.metrics.Recall(name="recall")]
)

#/content/drive/MyDrive/muan11/best_brain_ResNet50_model.keras
# Callbacks
checkpoint_path = "/content/drive/MyDrive/Trained model/best_brain_ResNet50_model.keras"

callbacks = [
    EarlyStopping(monitor="val_loss", patience=6, restore_best_weights=True),
    ModelCheckpoint(filepath=checkpoint_path, monitor="val_accuracy", save_best_only=True),
    ReduceLROnPlateau(monitor="val_loss", factor=0.2, patience=2, min_lr=1e-6)
]

# Train Model
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=30,
    callbacks=callbacks
)

"""# Results v1

---------------------------------------------------------------------------------------
"""

import matplotlib.pyplot as plt
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

plt.figure(figsize=(8,5))
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Training vs Validation Accuracy')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(8,5))
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training vs Validation Loss')
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report

def evaluate_model(model, generator, title="Confusion Matrix"):
    generator.reset()

    preds = model.predict(generator, verbose=1)
    pred_classes = np.argmax(preds, axis=1)
    true_classes = generator.classes
    class_names = list(generator.class_indices.keys())

    # Confusion Matrix
    cm = confusion_matrix(true_classes, pred_classes)
    plt.figure(figsize=(7, 6))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    disp.plot(cmap="Blues", values_format="d")
    plt.title(title)
    plt.xticks(rotation=45)
    plt.show()

    # Classification Report
    print(f"===== {title.upper()} CLASSIFICATION REPORT =====\n")
    print(classification_report(true_classes, pred_classes, target_names=class_names))

evaluate_model(
    model,
    validation_generator,
    title="Validation Confusion Matrix"
)

import os
model_dir = "/content/drive/MyDrive/Trained model"
print("Files inside model directory:\n")
for file in os.listdir(model_dir):
    print(file)
# output => best_brain_ResNet50_model.keras

import tensorflow as tf

MODEL_PATH = "/content/drive/MyDrive/Trained model/best_brain_ResNet50_model.keras"

model = tf.keras.models.load_model(MODEL_PATH)

print("✅ Best model loaded successfully.")

model.summary()

import numpy as np
from tensorflow.keras.preprocessing import image

img_path = "/content/drive/MyDrive/brain_tumor_testing_CLAHE/meningioma/Te-me_0012.jpg"

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)

img_array = np.expand_dims(img_array, axis=0)
img_array = img_array / 255.0

prediction = model.predict(img_array)

print(prediction)
# [[0.98 0.01 0.00 0.01]]

class_names = [
    "glioma",
    "meningioma",
    "notumor",
    "pituitary"
]

predicted_class = class_names[np.argmax(prediction)]

confidence = np.max(prediction)

print(f"Predicted Class : {predicted_class}")
print(f"Confidence      : {confidence:.2%}")
# Predicted Class : glioma
# Confidence      : 99.41%

# brain_tumor_testing_CLAHE/
# │
# ├── glioma
# ├── meningioma
# ├── notumor
# └── pituitary

from tensorflow.keras.preprocessing.image import ImageDataGenerator

TEST_DIR = "/content/drive/MyDrive/brain_tumor_testing_CLAHE"

test_datagen = ImageDataGenerator(
    rescale=1./255
)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=(224,224),
    batch_size=32,
    class_mode='categorical',
    shuffle=False
)

print("="*50)
print("Number of Test Images :", test_generator.samples)
print("Batch Size            :", test_generator.batch_size)
print("Number of Classes     :", test_generator.num_classes)

print("\nClass Indices:")
print(test_generator.class_indices)
print("="*50)

results = model.evaluate(
    test_generator,
    verbose=1
)

print("\nEvaluation Results")
print("-"*40)

for name, value in zip(model.metrics_names, results):
    print(f"{name:15s}: {value:.4f}")

import numpy as np

predictions = model.predict(
    test_generator,
    verbose=1
)

predicted_classes = np.argmax(predictions, axis=1)

true_classes = test_generator.classes

class_names = list(test_generator.class_indices.keys())

from sklearn.metrics import classification_report

print(
    classification_report(
        true_classes,
        predicted_classes,
        target_names=class_names,
        digits=4
    )
)

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

accuracy = accuracy_score(
    true_classes,
    predicted_classes
)

precision = precision_score(
    true_classes,
    predicted_classes,
    average='weighted'
)

recall = recall_score(
    true_classes,
    predicted_classes,
    average='weighted'
)

f1 = f1_score(
    true_classes,
    predicted_classes,
    average='weighted'
)

print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(
    true_classes,
    predicted_classes
)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted Class")
plt.ylabel("True Class")
plt.title("Confusion Matrix (Test Set)")

plt.tight_layout()

plt.show()

from sklearn.preprocessing import label_binarize

true_binary = label_binarize(
    true_classes,
    classes=[0,1,2,3]
)

from sklearn.metrics import roc_curve
from sklearn.metrics import auc

plt.figure(figsize=(8,8))

colors = ['blue','red','green','orange']

for i, color in enumerate(colors):

    fpr, tpr, _ = roc_curve(
        true_binary[:,i],
        predictions[:,i]
    )

    roc_auc = auc(fpr, tpr)

    plt.plot(
        fpr,
        tpr,
        color=color,
        lw=2,
        label=f"{class_names[i]} (AUC = {roc_auc:.3f})"
    )

plt.plot(
    [0,1],
    [0,1],
    linestyle='--',
    color='black'
)

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title("Multi-class ROC Curve")

plt.legend()

plt.grid(True)

plt.show()

print("FINAL TEST RESULTS")


print(f"Test Accuracy : {accuracy:.4f}")
print(f"Precision     : {precision:.4f}")
print(f"Recall        : {recall:.4f}")
print(f"F1 Score      : {f1:.4f}")

import os
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing import image

for layer in model.layers:
    print(layer.name)

LAST_CONV_LAYER = "conv5_block3_out"

LAST_CONV_LAYER = "conv5_block3_out"

def make_gradcam_heatmap(img_array, model, last_conv_layer):

    grad_model = tf.keras.models.Model(
        inputs=model.inputs,
        outputs=[
            model.get_layer(last_conv_layer).output,
            model.output
        ]
    )

    with tf.GradientTape() as tape:

        conv_outputs, predictions = grad_model(img_array)

        pred_index = tf.argmax(predictions[0])

        class_channel = predictions[:, pred_index]

    grads = tape.gradient(class_channel, conv_outputs)

    pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))

    conv_outputs = conv_outputs[0]

    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]

    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap,0)

    heatmap /= tf.reduce_max(heatmap)

    return heatmap.numpy()

def overlay_heatmap(img_path, heatmap, alpha=0.4):

    img = cv2.imread(img_path)

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    heatmap = cv2.resize(
        heatmap,
        (img.shape[1], img.shape[0])
    )

    heatmap = np.uint8(255*heatmap)

    heatmap = cv2.applyColorMap(
        heatmap,
        cv2.COLORMAP_JET
    )

    heatmap = cv2.cvtColor(
        heatmap,
        cv2.COLOR_BGR2RGB
    )

    overlay = cv2.addWeighted(
        img,
        1-alpha,
        heatmap,
        alpha,
        0
    )

    return img, heatmap, overlay

CLASS_NAMES = [
    "glioma",
    "meningioma",
    "notumor",
    "pituitary"
]

OUTPUT_DIR = "/content/drive/MyDrive/GradCAM_Results"

os.makedirs(OUTPUT_DIR, exist_ok=True)

for c in CLASS_NAMES:
    os.makedirs(
        os.path.join(OUTPUT_DIR,c),
        exist_ok=True
    )

import random

TEST_DIR = "/content/drive/MyDrive/brain_tumor_testing_CLAHE"

NUM_IMAGES_PER_CLASS = 2
IMG_SIZE = (224,224)

for class_name in CLASS_NAMES:

    class_dir = os.path.join(TEST_DIR, class_name)

    images = sorted(os.listdir(class_dir))

    selected_images = random.sample(
        images,
        min(NUM_IMAGES_PER_CLASS, len(images))
    )

    print("="*70)
    print(f"Processing Class : {class_name}")
    print("="*70)

    for img_name in selected_images:

        img_path = os.path.join(class_dir, img_name)

        img = image.load_img(
            img_path,
            target_size=IMG_SIZE
        )

        img_array = image.img_to_array(img)

        img_array = np.expand_dims(img_array,0)

        img_array = img_array/255.

        preds = model.predict(
            img_array,
            verbose=0
        )

        pred_index = np.argmax(preds)

        confidence = preds[0][pred_index]

        pred_label = CLASS_NAMES[pred_index]

        heatmap = make_gradcam_heatmap(
            img_array,
            model,
            LAST_CONV_LAYER
        )

        original, heatmap_img, overlay = overlay_heatmap(
            img_path,
            heatmap
        )

        plt.figure(figsize=(15,5))

        plt.subplot(1,3,1)
        plt.imshow(original)
        plt.axis("off")
        plt.title("Original")

        plt.subplot(1,3,2)
        plt.imshow(heatmap_img)
        plt.axis("off")
        plt.title("Grad-CAM")

        plt.subplot(1,3,3)
        plt.imshow(overlay)
        plt.axis("off")
        plt.title("Overlay")

        plt.suptitle(
            f"True : {class_name} | Pred : {pred_label} | Confidence : {confidence:.2%}",
            fontsize=13
        )

        plt.tight_layout()

        save_path = os.path.join(
            OUTPUT_DIR,
            class_name,
            img_name
        )

        plt.savefig(
            save_path,
            dpi=300,
            bbox_inches="tight"
        )

        plt.show()

        plt.close()

correct = (class_name == pred_label)

title_color = "green" if correct else "red"

fig, axes = plt.subplots(
    1,
    3,
    figsize=(10, 3.5),
    dpi=150
)

titles = ["Original", "Grad-CAM", "Overlay"]
images_to_show = [original, heatmap_img, overlay]

for ax, img_show, title in zip(axes, images_to_show, titles):

    ax.imshow(img_show)

    ax.set_title(
        title,
        fontsize=11,
        fontweight="bold"
    )

    ax.axis("off")

fig.suptitle(
    f"Image: {img_name}\n"
    f"True: {class_name}    |    "
    f"Predicted: {pred_label}    |    "
    f"Confidence: {confidence:.2%}",
    fontsize=12,
    fontweight="bold",
    color=title_color,
    y=1.03
)

plt.tight_layout()

save_path = os.path.join(
    OUTPUT_DIR,
    class_name,
    img_name
)

plt.savefig(
    save_path,
    dpi=300,
    bbox_inches="tight",
    facecolor="white"
)

plt.show()

plt.close()